settings:
  render_distance: 50
  refresh_cooldown: 20

menu:

  exit: "<gradient:#FA7CBB:#F14658>Exit"
  back: "<gradient:#FA7CBB:#F14658>Back"

  categories:

    ores:
      name: "<gradient:#59A7EA:#F1D2FF><bold>Ores"
      item: "minecraft:diamond_ore"
      blocks:

        coal_ore:
          name: "<#0f0f0f>■ <#d5d9db>Coal"
          type: "minecraft:coal_ore"
          color: 15, 15, 15, 200
        deepslate_coal_ore:
          name: "<#0f0f0f>■ <#d5d9db>Deepslate Coal"
          type: "minecraft:deepslate_coal_ore"
          color: 15, 15, 15, 240

        iron_ore:
          name: "<#ffb273>■ <#d5d9db>Iron"
          type: "minecraft:iron_ore"
          color: 255, 178, 115, 200
        deepslate_iron_ore:
          name: "<#ffb273>■ <#d5d9db>Deepslate Iron"
          type: "minecraft:deepslate_iron_ore"
          color: 255, 178, 115, 240

        copper_ore:
          name: "<#ff8640>■ <#d5d9db>Copper"
          type: "minecraft:copper_ore"
          color: 255, 134, 64, 200
        deepslate_copper_ore:
          name: "<#ff8640>■ <#d5d9db>Deepslate Copper"
          type: "minecraft:deepslate_copper_ore"
          color: 255, 134, 64, 240

        gold_ore:
          name: "<#fadf32>■ <#d5d9db>Gold"
          type: "minecraft:gold_ore"
          color: 250, 223, 50, 200
        deepslate_gold_ore:
          name: "<#fadf32>■ <#d5d9db>Deepslate Gold"
          type: "minecraft:deepslate_gold_ore"
          color: 250, 223, 50, 240

        redstone_ore:
          name: "<#fa3232>■ <#d5d9db>Redstone"
          type: "minecraft:redstone_ore"
          color: 250, 50, 50, 200
        deepslate_redstone_ore:
          name: "<#fa3232>■ <#d5d9db>Deepslate Redstone"
          type: "minecraft:deepslate_redstone_ore"
          color: 250, 50, 50, 240

        emerald_ore:
          name: "<#27e37e>■ <#d5d9db>Emerald"
          type: "minecraft:emerald_ore"
          color: 39, 227, 126, 200
        deepslate_emerald_ore:
          name: "<#27e37e>■ <#d5d9db>Deepslate Emerald"
          type: "minecraft:deepslate_emerald_ore"
          color: 39, 227, 126, 240

        lapis_ore:
          name: "<#1f57cf>■ <#d5d9db>Lapis"
          type: "minecraft:lapis_ore"
          color: 31, 87, 207, 200
        deepslate_lapis_ore:
          name: "<#1f57cf>■ <#d5d9db>Deepslate Lapis"
          type: "minecraft:deepslate_lapis_ore"
          color: 31, 87, 207, 240

        diamond_ore:
          name: "<#0fd3ff>■ <#d5d9db>Diamond"
          type: "minecraft:diamond_ore"
          color: 15, 211, 255, 200
        deepslate_diamond_ore:
          name: "<#0fd3ff>■ <#d5d9db>Deepslate Diamond"
          type: "minecraft:deepslate_diamond_ore"
          color: 15, 211, 255, 240

        nether_gold_ore:
          name: "<#fadf32>■ <#d5d9db>Nether Gold"
          type: "minecraft:nether_gold_ore"
          color: 250, 223, 50, 200

        nether_quartz_ore:
          name: "<#e6e6e6>■ <#d5d9db>Nether Quartz"
          type: "minecraft:nether_quartz_ore"
          color: 230, 230, 230, 200


    containers:
      name: "<gradient:#FAD6A6:#F1D2FF><bold>Containers"
      item: "minecraft:chest"
      blocks:
        chest:
          name: "<#ffc83d>■ <#d5d9db>Chest"
          type: "minecraft:chest"
          color: 255, 200, 61, 240
        trapped_chest:
          name: "<#ff6e3d>■ <#d5d9db>Trapped Chest"
          type: "minecraft:trapped_chest"
          color: 255, 110, 61, 240


    redstone:
      name: "<gradient:#FA7CBB:#F14658><bold>Redstone"
      item: "minecraft:redstone"
      blocks:
        redstone:
          name: "<#ff3d3d>■ <#d5d9db>Redstone Block"
          type: "minecraft:redstone_block"
          color: 255, 61, 61, 220


    misc:
      name: "<gradient:#737DFE:#FFCAC9><bold>Misc"
      item: "minecraft:spawner"
      blocks:
        spawner:
          name: "<#9700c4>■ <#d5d9db>Spawner"
          type: "minecraft:spawner"
          color: 151, 0, 196, 255